### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by ivanpricewaycom** [SalesforceFoundation/salesforce-requests-oauthlib#2]
Hi there,

a couple of modules aren't present in python 3, would it be possible to add the following to support both python 2 and 3 (file salesforce_requests_oauthlib/__init__.py )

cheers and thankyou

-ivan

```
35,36c35,42
< import BaseHTTPServer
< import thread
---
> try:
>     import BaseHTTPServer
> except ImportError:
>     import http.server as BaseHTTPServer
> try:
>     import thread
> except ImportError:
>     import _thread as thread
```

**Comment by adamlincoln** [comment]
Just released to pypi (version 0.1.1).  Thanks @ivanpricewaycom !
